<center><img src="poster.png" width="800"/></center>

# Lecture 1: Exercises

## Exercise 1

Write a Pyhton program using NumPy to:
1. Create a 7×7 array with 1 on the first and last rows and columns and 0 elsewhere.
2. Create an 8 × 8 array with ones on a diagonal and zeros elsewhere.
3. Create a 5 × 5 matrix with row values ranging from 0 to 4.
4. Compute the multiplication of two random 10 × 10 matrices.
5. Compute the determinant of a random 100 × 100 square array.

In [20]:
import numpy as np

In [30]:
A = np.array([[1, 1, 1, 1, 1, 1, 1],
             [1, 0, 0, 0, 0, 0, 1],
             [1, 0, 0, 0, 0, 0, 1],
              [1, 0, 0, 0, 0, 0, 1],
              [1, 0, 0, 0, 0, 0, 1],
              [1, 0, 0, 0, 0, 0, 1],
              [1, 1, 1, 1, 1, 1, 1]])
print(A)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [34]:
B = np.eye(8)
print(B)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [60]:
C = np.random.randint(5, size = (5,5))
print(C)

[[3 4 3 0 2]
 [3 3 0 1 1]
 [2 2 1 3 4]
 [2 4 1 2 3]
 [1 0 1 4 2]]


In [68]:
D = np.random.randint(10, size = (10,10))
E = np.random.randint(10, size = (10,10))
F = D*E
print(D, E, F)

[[1 5 5 9 8 1 7 6 1 1]
 [6 6 7 0 1 7 7 0 2 4]
 [7 3 3 4 0 0 5 4 1 8]
 [2 1 9 1 7 5 6 0 6 0]
 [7 6 5 1 0 3 9 4 2 0]
 [0 9 9 1 1 7 0 5 0 3]
 [1 6 1 1 4 6 3 8 7 8]
 [4 1 7 6 3 4 4 0 8 8]
 [6 5 5 5 7 3 6 2 4 2]
 [7 7 5 1 9 8 9 4 9 0]] [[6 9 7 3 2 6 9 4 8 0]
 [5 0 2 5 5 8 0 6 8 0]
 [0 8 8 6 7 6 0 5 9 6]
 [9 4 9 0 1 8 7 1 2 6]
 [0 9 1 7 9 8 7 0 1 0]
 [5 7 4 0 6 1 8 0 5 0]
 [8 6 9 7 7 7 5 9 0 4]
 [5 3 6 0 2 0 4 4 2 5]
 [7 6 1 7 2 0 2 4 7 2]
 [3 2 9 8 2 7 8 2 3 9]] [[ 6 45 35 27 16  6 63 24  8  0]
 [30  0 14  0  5 56  0  0 16  0]
 [ 0 24 24 24  0  0  0 20  9 48]
 [18  4 81  0  7 40 42  0 12  0]
 [ 0 54  5  7  0 24 63  0  2  0]
 [ 0 63 36  0  6  7  0  0  0  0]
 [ 8 36  9  7 28 42 15 72  0 32]
 [20  3 42  0  6  0 16  0 16 40]
 [42 30  5 35 14  0 12  8 28  4]
 [21 14 45  8 18 56 72  8 27  0]]


In [72]:
from numpy.linalg import det
G = np.random.randint(10, size = (100,100))
print(G,det(G))

[[4 2 9 ... 1 6 4]
 [8 9 8 ... 3 6 0]
 [8 2 3 ... 4 1 5]
 ...
 [0 5 4 ... 4 1 0]
 [7 4 7 ... 3 9 7]
 [9 3 4 ... 7 4 8]] 1.624885815482087e+125


## Exercise 2

Write the commands for each of the following operations:
1. Create a row vector $x$ of 5 equally spaced elements between 2 and 3.
2. Add 1 to the second element
3. Create a second row vector $y$ of the same dimension with elements equal to the successive even integers starting with 4.
4. Create the matrix $A$, whose first row is equal to $x$, whose second row is a line of ones, and whose third row is equal to $y$.
5. Define a row vector $z$, whose elements are equal to the mean value of the columns of $A$.

In [90]:
x = np.linspace(2,3,5)
print(x)
x[0] = x[0]+1
print(x)
y = [4, 5, 6, 7, 8]
A = np.zeros((3,5))
A[0,:] = x
A[1,:] = 1
A[2,:] = y
print(A)
z = np.array([np.mean(A[:,0]), np.mean(A[:,1]), np.mean(A[:,2])])
print(z)

[2.   2.25 2.5  2.75 3.  ]
[3.   2.25 2.5  2.75 3.  ]
[[3.   2.25 2.5  2.75 3.  ]
 [1.   1.   1.   1.   1.  ]
 [4.   5.   6.   7.   8.  ]]
[2.66666667 2.75       3.16666667]


## Exercise 3

Create two matrices A and B: $$A=\left(\begin{array}{cc}
    1 & 2  \\
    4 & -1  \\
\end{array}\right) \text{ and } B=\left(\begin{array}{cc}
    4 & -2  \\
    -6 & 3  \\
\end{array}\right).$$

1. Compute the matrices $C_1 = A + B$ and $C_2 = A − B$.
2. Compute the matrix products $D_1 = A \cdot B$ and $D_2 = B \cdot A$ (element wise).
3. Are A and B singular? If not, then compute their inverse.

In [112]:
A = np.array([[1,2], [4,-1]])
B = np.array([[4,-2], [-6,3]])
print(A,B)
C1 = A+B
C2 = A-B
D_1 = A@B
D_2 = B*A
print(D_2)

[[ 1  2]
 [ 4 -1]] [[ 4 -2]
 [-6  3]]
[[  4  -4]
 [-24  -3]]


In [114]:
import numpy.linalg as npl
Ainv = npl.inv(A)
Binv = npl.inv(B)
print(Ainv, Binv)

[[ 0.11111111  0.22222222]
 [ 0.44444444 -0.11111111]] [[-4.50359963e+15 -3.00239975e+15]
 [-9.00719925e+15 -6.00479950e+15]]
