<center><img src="poster.png" width="800"/></center>

# Lecture 1: Introduction to Python

## Scientic Computing and Numerical Analysis

#### For the purpose of scientific computing, a ``math book is not enough'' - G. Forsyth


#### In order to get the real essence of scientific computing and numerical analysis, some coding and experimentation are important.

## Python - History

Python is a high-level programming language celebrated for its simplicity, readability, and versatility. 

1989: Guido van Rossum develops Python <br> 1991 : Python is published <br> 1994: First official released of Python Version 1

### Which Companies Use Python?

Uber, Goldman Sachs, PayPal, Netflix, Google, NASA, Instagram, Spotify, Pinterest, and more. <br> Python is also the command language for a large number of free software programs: FreeCAD, 3DBlender, Inkscape, LibreOffice, Gentoo, ParaView, XBMC, EVE Online...

### PYPL PopularitY of Programming Language


<img src="pypl ranking.png" width="500"/>


### TIOBE Index for January 2025

<img src="tiobe1.png" width="500"/>

<img src="tiobe.png" width="800"/>

## Why Python?

<ul>
<li>A free and portable language on any system (Windows, Mac, Linux)</li>
<li>Not the fastest but it can be interfaced with other more powerful languages (Fortran: f2py, C: swig, boost ...)</li>
<li>Easily integrate existing calculation codes (Fortran, C, ...), make them accessible, process their results graphically, continue their developments...</li>
<li>Already optimized libraries and a large selection of libraries</li>
<li>Other languages accessible by python (Java : Jython)</li>
<li>Has a helpful "community" platform</li>
<li>Nothing to declare, automatic memory management</li>
<li>Object-oriented, interpreted and partially compiled</li>


</ul>

A large choice of libraries and open software, allowing to make :
<ul>
    <li>Web (Zope, Plone, Django, ...)</li>
    <li>Databases (MySQL, Oracle, ...), networks (PyRO, ...)</li>
    <li>Gui (Gtk, Qt, WxWidgets, ...)</li>
    <li>Graphics (gnuplot, matplotlib, VTK, MayaVi, ...)</li>
    <li>Scientific computing (Numpy, Scipy, SimPy, FiPy, Getfem, Sage, MDP...)</li>
    <li>Bioinformatics, Chemistry...</li>
</ul>

## Installation

Anaconda is a free and open source distribution of Python <br>
• Contains most of the libraries needed for teaching <br>
• Simplified installation and addition of libraries

Anaconda - https://www.anaconda.com/download

Google Collab - https://colab.research.google.com

## Basic Python - Python, numbers and variables

In [65]:
print('Hello world')

Hello world


Use `#` for a short, quick comment (or for debugging)

In [ ]:
# print("This is a comment.")
print("This is not a comment.")

The storage places in computer programming are called variables. We store numbers (and other values) in variables. A variable is an object that has a name, like variables in mathematics.

Variables in Python can contain letters (lower or upper case), numbers 0-9, and some special characters, e.g., underscore
- variable names should start with a letter
- be sure not to use reserved words, e.g., `print`, `if`, `for`

In [7]:
number_of_students = 50
print( number_of_students )
number_of_students = 40
print( number_of_students )

50
40


In [9]:
print( 'The number of students =', number_of_students ) 

The number of students = 40


In [11]:
number_of_students = input( 'Enter the number of students' )
print( 'The number of students = ', number_of_students ) 

Enter the number of students 60


The number of students =  60


Python integers have unlimited precision -- there is no limit on the size of the integer, but it can be slow.

In [16]:
a = 4379857389751098475175089217
b = 4738574387589234759871587109580941579496787754315
print(a * b * b * a)

430740140326085856294542631928555788313067344826842766627319926066587103283094870058228633072524398034207389449610176808454714697112851095693035063036025


Python floats, however, have limits. For double precision (which is used by default) you get an exponent (of 2) between -1022 and +1023 (-307 to 308 base 10) and ~16 decimal places.

In [19]:
print(11.5473895**250)
print(11.5473895**350)

4.177858869331092e+265


OverflowError: (34, 'Result too large')

## Basic mathematical operations

We can perform very simple calculations such as 1 + 2 by just typing 1+2 in a Jupyter notebook and pressing shift+return.

<center><img src="Arithmetic table.png" width="400"/></center>


In [92]:
# Examples of Arithmetic Operators
x = 11
y = 2
# Addition of numbers
add = x + y
# Subtraction of numbers
sub = x - y
# Multiplication of numbers
mul = x * y
# Division (float) of numbers
div1 = x / y
# Division (floor) of numbers
div2 = x // y
# Modulo of both numbers
mod = x % y
# Raise to power
pow = x ** y
# print results
print( 'add = ', add )
print( 'sub = ', sub )
print( 'mul = ', mul )
print( 'div1 = ', div1 )
print( 'div2 = ', div2 )
print( 'mod = ', mod )
print( 'pow = ', pow )

add =  13
sub =  9
mul =  22
div1 =  5.5
div2 =  5
mod =  1
pow =  121


In [94]:
a = 1 + 2 * 3; b = (1 + 2) * 3; c = 2**2 * 3
print(a,b,c)

7 9 12


If we want to increase the value of the variable $x$ by 1 the syntax is $x = x + 1$. If we want to decrease the value of the variable $x$ by 3 the syntax is $x = x - 3$. We type $x = 2 * x$ to double its value or $x = x/3.0$ to divide by 3. All these expressions are not equations but assignments. The operator = assigns the value of the right-hand side to the variable on left-hand side.

#### Be careful with floats: operations are not exact, just like in C/C++:

In [26]:
print(0.2 + 0.1 == 0.3)

False


# Comparison Operators

In [ ]:
bool(0) # false
bool(1) # true

a = 0
b = 1

print(a < b)  # strictly less than
print(a <= b) # less than or equal

print(a > b)  # strictly greater than
print(a >= b) # greater than or equal

print(a == b) # equal
print(a != b) # not equal

# Getting HELP

`help()` command usually tells you everything you need to know about the object.

In [ ]:
help('string')

## Mathematical functions and constants

There are many different Python modules. Mathematical functions can be found in the module **math** as well as in the module **numpy**. For efficiency reasons, modules are not loaded automatically. We can load an entire module (library of functions) using the command

In [109]:
#Use one of the following

# import math
# from math import *
# import math as mt (this one is recommended)

In [44]:
import math as mt
print( mt.sin(mt.pi/5) )

0.5877852522924731


`math.exp()`, `math.pow()` `math.sqrt()` `math.log()` `math.log2()` `math.log10()` `math.cos()` `math.sin()` `math.tan()` `math.acos()` `math.asin()` `math.atan()` `math.pi()` `math.e()` `math.tau()`

In [48]:
mt.sin(mt.pi/2)
mt.sqrt(2)

1.4142135623730951

## Data structures - Strings

These structures are the following: **Strings** that resemble text messages, **tuples**, which can combine more than one variable of different types, and **lists**, which can be seen as vectors or sequences of similar objects.

A **string** (or alpharithmetic) is a sequence of characters (letters, numbers and symbols) enclosed in single or double quotes. We can use strings when we want to display messages on the screen.

In [131]:
print( 'Hello world!' )

Hello world!


In [133]:
my_name = 'James'
my_lastname = 'Bond'
full_name = my_name + ' ' + my_lastname
print( full_name )

James Bond


In [135]:
my_name = 'James'
print( my_name[:] )
print( my_name[0:5] )
print( my_name[:5] )
print( my_name[3:] )

James
James
James
es


Remark:  In Python we start counting from 0. The slice operator : can be used as follows **start:stop** where **start** is the value from which we start counting and **stop-1** is where we want to stop. We say that Python is not inclusive. Python accesses the entire array when we use the slice operator : without specifying where to start and where to stop. If we don't provide the value start then this is taken 0. If we do not provide the value stop, then the counter will reach the last entry.

## Data structures - Tuples

A **tuple** is a sequence of (not necessarily same) objects separated with commas. For clarity, tuples are usually enclosed in parentheses. For example, a tuple can be the combination 2,`Hi' or (2,`Hi'), where its first entry is the number 2 and its second entry is `Hi'. Tuples can be useful when we want to return more than one object in a function.

In [140]:
x = ( 2, 'Hi' )
print( x[0] )
print( x[1] )

2
Hi


In [61]:
t = ()                # or t = tuple(), this is empty tuple
t = tuple(range(10))  #create tuple from a list
print(t)
print(t[4::2])        #can use indexing and slicing
t = tuple("string")   #can create from the string
print(t)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
(4, 6, 8)
('s', 't', 'r', 'i', 'n', 'g')


## Data structures - Lists

A **list** is a data structure that resembles a vector and contains data linked as in a chain. Lists can change size by adding entries anywhere we like. The list can contain only objects of the same type (i.e. numbers only, or strings only, etc.).

In [155]:
list = [5, 3, 7]
print(list[0])
print(list[1])
print(list[2])

5
3
7


a list is a periodic structure, make changes to an entry of a list, add a new entry at the end of a list

In [157]:
list = [5, 3, 7]
print(list[-1])

7


In [159]:
list[1] = 9
print(list)

[5, 9, 7]


In [161]:
list.append(10)
print(list)

[5, 9, 7, 10]


In [165]:
grades = [9.0, 6.7, 8.5, 7.6, 9.8, 7.0]
n = len(grades)
print(n)

6


add new entries to the end of the list using the operator +, 

In [176]:
grades = grades + [6.2, 8.2, 5.9]
print(grades)

[9.0, 6.7, 8.5, 7.6, 9.8, 7.0, 6.2, 8.2, 5.9]


The slice operator : can be used again in order to extract certain parts of a list.

In [178]:
print(grades[2:5])

[8.5, 7.6, 9.8]


Adding two lists results in a new list

In [180]:
list1 = [9, 6, 8, 7]
list2 = [1, 2, 3]
list3 = list1 + list2
print(list3)

[9, 6, 8, 7, 1, 2, 3]


## Data structures - List of list

Python does not have a built-in type for matrices. However, we can think of a matrix in Python as a list of lists. The entries of this list (matrix) represent the matrix rows and are lists. For example, the matrix 
$$A=\left(\begin{array}{cc}
        1 & 2 \\
        3 & 4
    \end{array}\right),$$ is represented in Python as A = [[1,2],[3,4]].

In [189]:
A = [[1,2],[3,4]]
print(A)

[[1, 2], [3, 4]]


access the entry of the Pythonic matrix

In [192]:
a12 = A[0][1]
print(a12)

2


Remakrs: For scientific computations with matrices we use a different data structure called **array**. This data structure is similar to the Pythonic list of lists but is equipped with the usual linear algebra properties and operations. For this reason, we focus on matrix computations using **arrays**.

## Matrices and Python - The NumPy module

NumPy is a Python module that defines a number of data structures and functions specialized for scientific computing. Like every other module, we need to import its functions in the beginning of our code. This can be done with one of the following commands:

In [211]:
# Use only one of the following

# import numpy
# import numpy as np
# from numpy import *
# from numpy import function

We usually import the module numpy in the beginning of our code. Most commonly, NumPy is imported via the command **import numpy as np**. NumPy's most important data structures is the n-dimensional array ndarray.

A NumPy array is very similar to a list of lists and is actually constructed by a list of lists. We can define the simple $3 \times  2$ matrix $A=\left(\begin{array}{cc}
        1 & 2 \\
        3 & 4 \\
        5 & 6
    \end{array}\right)$ using the function np.array and appropriate list of lists as input. The output will be a new array. In Python (and also in NumPy) indices start from 0. 

In [68]:
import numpy as np

A = np.array( [[1, 2], [3, 4], [5, 6]] )
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [217]:
print("a(1,2) = ", A[0,1])

a(1,2) =  2


To modify the value of the entry

In [219]:
A[1,1]=10
print(A)

[[ 1  2]
 [ 3 10]
 [ 5  6]]


In [222]:
A[0,1] = A[0,1] + 1
print(A)

[[ 1  3]
 [ 3 10]
 [ 5  6]]


## Matrices and Python - Slicing

The slice operator : can be used to extract parts of a NumPy array.

In [254]:
A = np.array( [[1, 2], [3, 4], [5, 6]] )
print(A[:,0])
print(type(A[:,0]))

[1 3 5]
<class 'numpy.ndarray'>


we can extract rows instead of columns

In [ ]:
print(A[1,:])

For example, consider the following $3\times 3$ matrix
$B=\left(\begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9 \\
\end{array}\right),$ for which we extract the $2\times 2$ block consisting of the first 2 columns and 2 rows $C = \left(\begin{array}{cc}
    1 & 2 \\
    4 & 5
\end{array}\right)$, using the following lines of code

In [237]:
B = np.array( [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]] )
C = B[0:2, 0:2]
print(C)

[[1 2]
 [4 5]]


## Matrices and Python - Vectors and arrays

consider the vector $a = (1, 2, 3)$ as a $1\times3$ matrix:

In [241]:
a = np.array( [[1, 2, 3]] )
print(a.shape)

(1, 3)


Here we call vectors (row or column) arrays with shape ($n,)$ instead of $(n,1)$ or $(1,n)$. This can be done by using single square brackets instead of double in the definition of an array:

In [256]:
a = np.array( [1, 2, 3] )
print(a.shape)

(3,)


In [258]:
print(a[1])

2


use the command reshape

In [260]:
b = a.reshape((1,3))
c = a.reshape((1,-1))
print('b=', b)
print(b.shape)
print('c=', c)
print(c.shape)

b= [[1 2 3]]
(1, 3)
c= [[1 2 3]]
(1, 3)


## Special matrices, methods and properties

create automatically an $n\times m$ matrix with all entries zero

In [263]:
A = np.zeros( (3,4) )
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [265]:
print(np.shape(A))
print(A.ndim)
print(A.size)

(3, 4)
2
12


we create a $3\times3$ identity matrix by typing

In [267]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


create an $n\times m$ matrix full of ones

In [284]:
A = np.ones( (3,2) )
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


we can extract the upper and lower triangular parts of a matrix by typing

In [286]:
A = np.array( [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]] )
L = np.tril(A)
U = np.triu(A)
print('A = '); print(A)
print('L = '); print(L)
print('U = '); print(U)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
L = 
[[1 0 0]
 [4 5 0]
 [7 8 9]]
U = 
[[1 2 3]
 [0 5 6]
 [0 0 9]]


generate its transpose matrix

In [288]:
A = np.array( [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]] )
B = np.transpose(A)
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


add two or more matrices

In [292]:
A = np.array( [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]] )
B = np.array( [[9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]] )
C = A + B
print(C)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


The matrix C is a new matrix and is unrelated to A and B. In the same way we can subtract, multiply a matrix with a scalar etc. For example, we can write

In [294]:
D = A - B
E = 2.0 * A
F = C / 2.0
G = A - 3.0*F
print(D)
print(E)
print(F)
print(G)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[-14. -13. -12.]
 [-11. -10.  -9.]
 [ -8.  -7.  -6.]]


## Matrix multiplication

The operator $*$ with NumPy arrays does not perform an actual matrix multiplication. It performs an element by element multiplication between two arrays. On the other hand, the operator $@$ performs the usual matrix multiplication. For example,

In [297]:
A = np.array( [[1, 2],
    [3, 4]] )
B = np.array( [[5, 6],
    [7, 8]] )
C = A * B
print('C='); print(C)
D = A @ B
print('D='); print(D)

C=
[[ 5 12]
 [21 32]]
D=
[[19 22]
 [43 50]]


Matrix multiplication can be also performed using the NumPy function dot.

In [315]:
A = np.array( [[1, 2],
    [3, 4]] )
B = np.array( [[5, 6, 7],
               [8, 9, 10]] )
C = np.dot(A,B)
print(C)

[[21 24 27]
 [47 54 61]]


## Inverse matrix, determinant of a matrix

Computation of the inverse of a matrix A

In [318]:
import numpy.linalg as npl

A = np.array( [[1, 2],
[3, 4]] )
Ainv = npl.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


A determinant of a matrix can be computed approximately using the function \textbf{det} of the module numpy.linalg. For example,

In [321]:
import numpy as np
from numpy.linalg import det
A = np.array( [[ 1, 4, 2, 3],
    [ 0, 1, 4, 4],
    [-1, 0, 1, 0],
    [ 2, 0, 4, 1]] )
print(det(A))

64.99999999999999


## Linear system

To solve numerically a system of linear equations $Ax = b$ we use NumPy and its function **solve**. For example, to solve the previous linear system we type

In [326]:
from numpy.linalg import solve
A = np.array( [[ 2.0, -1.0, 0.0 , 0.0],
    [-1.0, 3.0, -1.0, 0.0],
    [ 0.0, -1.0, 3.0, -1.0],
    [ 0.0, 0.0 ,-1.0, 2.0]] )
b = np.ones((4,1))
x = solve(A,b)
print(x)

[[1.]
 [1.]
 [1.]
 [1.]]


In [70]:
A = np.array([[1,77,3],[4,5,6],[7,8,9]])
B = np.linspace(5,30,6).reshape(3,2)
print('A:',A)
print('B:',B)
print('dot product\n',np.dot(A,B))
print('Matrix product\n',np.matmul(A,B)) #different from dot for dimensions>2
print('Inner product\n',np.inner(A,A))
print('Trace\n',np.trace(A))
print('Transpose\n',A.T)
print('Matrix Power\n',np.linalg.matrix_power(A,2))
print('Inverse\n',np.linalg.inv(A))
print('Determinant\n',np.linalg.det(A))

A: [[ 1 77  3]
 [ 4  5  6]
 [ 7  8  9]]
B: [[ 5. 10.]
 [15. 20.]
 [25. 30.]]
dot product
 [[1235. 1640.]
 [ 245.  320.]
 [ 380.  500.]]
Matrix product
 [[1235. 1640.]
 [ 245.  320.]
 [ 380.  500.]]
Inner product
 [[5939  407  650]
 [ 407   77  122]
 [ 650  122  194]]
Outer product
 [[   5.   10.   15.   20.   25.   30.]
 [ 385.  770. 1155. 1540. 1925. 2310.]
 [  15.   30.   45.   60.   75.   90.]
 [  20.   40.   60.   80.  100.  120.]
 [  25.   50.   75.  100.  125.  150.]
 [  30.   60.   90.  120.  150.  180.]
 [  35.   70.  105.  140.  175.  210.]
 [  40.   80.  120.  160.  200.  240.]
 [  45.   90.  135.  180.  225.  270.]]
Trace
 15
Transpose
 [[ 1  4  7]
 [77  5  8]
 [ 3  6  9]]
Matrix Power
 [[330 486 492]
 [ 66 381  96]
 [102 651 150]]
Inverse
 [[-0.00666667 -1.48666667  0.99333333]
 [ 0.01333333 -0.02666667  0.01333333]
 [-0.00666667  1.18       -0.67333333]]
Determinant
 450.00000000000006


## Statistics

In [343]:
x = np.array([3.5, 1.1, 3.2, 2.8, 6.7, 4.4, 0.9, 2.2])
A = np.mean(x)
B = np.median(x)
C = x.min()
D = x.max()
E = x.var()
F = x.std()
print(A, B, C, D, E, F)

3.1 3.0 0.9 6.7 3.0700000000000007 1.7521415467935233


In [ ]:
A = np.linspace(0,1,9)
print('A:',A)
print('sum:               ',np.sum(A))
print('product:           ',np.prod(A))
print('mean:              ',np.mean(A))
print('standard deviation:',np.std(A))
print('variance:          ',np.var(A))
print('minimum:           ',np.min(A))
print('maximum:           ',np.max(A))
print('median:            ',np.median(A))
print('index of min:      ',np.argmin(A))
print('index of max:      ',np.argmax(A))

## Random Numbers

In [20]:
import numpy as np
np.random.rand()

0.11093899749009617

In [18]:
np.random.randn()

0.6831356136047286

In [25]:
np.random.rand(5)

array([0.79237218, 0.39233412, 0.09576777, 0.91429581, 0.78702996])

In [27]:
np.random.randn(2, 4)

array([[ 0.21069651,  0.6832547 ,  0.91718557,  0.15575058],
       [-1.38648664,  0.57447951,  1.52903377,  0.85133039]])

In [30]:
np.random.randint(10, size=10)

array([4, 5, 1, 4, 1, 0, 7, 1, 9, 2])

In [33]:
np.random.randint(low=10, high=20, size=(2, 10))

array([[19, 10, 12, 17, 15, 14, 16, 16, 19, 10],
       [11, 15, 18, 15, 18, 11, 14, 17, 16, 17]])

## References

1.	Mitsotakis, Dimitrios. (2023). Computational Mathematics: An introduction to Numerical Analysis and Scientific Computing with Python. CRC Press
2. Johansson, Robert. (2019). Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib. Second Edition. Apress Media LLC: Welmoed Spahr