# Lecture 1: Exercises

## Exercise 1

Write a Pyhton program using NumPy to:
1. Create a 7×7 array with 1 on the first and last rows and columns and 0 elsewhere.
2. Create an 8 × 8 array with ones on a diagonal and zeros elsewhere.
3. Create a 5 × 5 matrix with row values ranging from 0 to 4.
4. Compute the multiplication of two random 10 × 10 matrices.
5. Compute the determinant of a random 100 × 100 square array.
6. Print a zero vector of size 10 but the fifth value which is 1
7. Create vector `z` with values ranging from 10 to 49
8. Print vector `z` in reverse order

In [ ]:
import numpy as np

In [ ]:
A = np.zeros((7,7))
# print(A)
A[0,0] = A[0,0]+1
A[0,1] = A[0,1]+1
A[0,2] = A[0,2]+1
A[0,3] = A[0,3]+1
A[0,4] = A[0,4]+1
A[0,5] = A[0,5]+1
A[0,6] = A[0,6]+1

A[1,0] = A[1,0]+1
A[2,0] = A[2,0]+1
A[3,0] = A[3,0]+1
A[4,0] = A[4,0]+1
A[5,0] = A[5,0]+1
A[6,0] = A[6,0]+1

A[6,1] = A[6,1]+1
A[6,2] = A[6,2]+1
A[6,3] = A[6,3]+1
A[6,4] = A[6,4]+1
A[6,5] = A[6,5]+1
A[6,6] = A[6,6]+1

A[1,6] = A[1,6]+1
A[2,6] = A[2,6]+1
A[3,6] = A[3,6]+1
A[4,6] = A[4,6]+1
A[5,6] = A[5,6]+1


print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
A = np.zeros((7,7))
A[0,:] = 1
A[6,:]=1
A[:,0] = 1
A[:,6]=1
print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
B= np.eye(8)
print(B)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
np.random.randint(0,4, size=(5,5))

array([[3, 2, 1, 0, 3],
       [2, 2, 3, 2, 1],
       [3, 1, 3, 1, 0],
       [0, 0, 2, 1, 3],
       [2, 0, 0, 2, 1]])

In [ ]:
A = np.random.randint(11, size=(10,10))
B = np.random.randint(11, size=(10,10))
C = A*B
print(A)
print(B)
print(C)

[[ 6  6 10  7  2  3  6  6  0  0]
 [ 2  9  6  6  9  9  2  2  5  6]
 [ 4  6  3  1  0  5  6  9  9  5]
 [ 0  5 10  3  3  4 10  0  1  9]
 [ 1  0  4  0  5  4  7  9  8  3]
 [ 8  4  0  4  9  9  0  7  2 10]
 [10  8  6  7  8 10  2  4 10  8]
 [ 4  9  1  9  0 10 10 10  3  8]
 [ 1  4  5  2  2  9  6  3  8  8]
 [ 6  0  9 10  5 10  0  7  4  2]]
[[ 4  5  5  7  3  6 10  7  1  6]
 [ 1  9  4  8  4  8  2  9  9  9]
 [ 4  6  4  5  4  0  5  5 10  4]
 [ 1  8  2  6  0  5  8 10  1  7]
 [10  0  3  1  8  7  2  3  7  6]
 [ 4  7  5  4  2  4  2  9  7  0]
 [ 5  9  3  4  2  7  6  7  2  3]
 [ 4  4  6  8  3  2  4  7  7  1]
 [ 6  6  8 10  2  7  2  6  5  8]
 [ 9  0  0  0  1  9  7 10  6  9]]
[[24 30 50 49  6 18 60 42  0  0]
 [ 2 81 24 48 36 72  4 18 45 54]
 [16 36 12  5  0  0 30 45 90 20]
 [ 0 40 20 18  0 20 80  0  1 63]
 [10  0 12  0 40 28 14 27 56 18]
 [32 28  0 16 18 36  0 63 14  0]
 [50 72 18 28 16 70 12 28 20 24]
 [16 36  6 72  0 20 40 70 21  8]
 [ 6 24 40 20  4 63 12 18 40 64]
 [54  0  0  0  5 90  0 70 24 18]]


In [ ]:
A = np.random.randint(50, size=(100,100))
B = np.linalg.det(A)
print(A)
print(B)

[[32 29 31 ...  7  1 42]
 [25  4 19 ...  3 17 49]
 [19 40 11 ... 11 39 17]
 ...
 [23 48 35 ... 26 26 21]
 [38 39 28 ...  3 19 31]
 [37 43 27 ...  4 41  1]]
-3.465100425972734e+194


In [ ]:
C = np.zeros(10)
C[4] =1
print(C)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.random.randint(low=10, high=49, size = 5)
X = np.flip(Z)
print(Z)
print(X)

[28 41 19 31 20]
[20 31 19 41 28]


In [ ]:
Z = np.random.randint(low=10, high=49, size = 5)
X = Z[::-1]
print(Z)
print(X)

[11 15 46 25 37]
[37 25 46 15 11]


## Exercise 2

Write the commands for each of the following operations:
1. Create a row vector $x$ of 5 equally spaced elements between 2 and 3.
2. Add 1 to the second element
3. Create a second row vector $y$ of the same dimension with elements equal to the successive even integers starting with 4.
4. Create the matrix $A$, whose first row is equal to $x$, whose second row is a line of ones, and whose third row is equal to $y$.
5. Define a row vector $z$, whose elements are equal to the mean value of the columns of $A$.
6. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.
7. Print a 10x10 array with 1 on the border and 0 inside

In [ ]:
import numpy as np

In [ ]:
A = np.linspace(2,3,5)
print(A)

[2.   2.25 2.5  2.75 3.  ]


In [ ]:
B = np.linspace(2,3,5)
B[1] = B[1]+1
print(B)

[2.   3.25 2.5  2.75 3.  ]


In [ ]:
C=np.linspace(4.0,12.0,5)
print(C)

[ 4.  6.  8. 10. 12.]


In [ ]:
D = np.ones(5)
print(D)

[1. 1. 1. 1. 1.]


In [ ]:
F = np.array([[A],[D],[C]])
print(F)

[[[ 2.    2.25  2.5   2.75  3.  ]]

 [[ 1.    1.    1.    1.    1.  ]]

 [[ 4.    6.    8.   10.   12.  ]]]


In [ ]:
G=np.mean(F,axis=0)
print(G)

[[2.33333333 3.08333333 3.83333333 4.58333333 5.33333333]]


In [ ]:
L=np.zeros((5,5))
L[1,0]=1
L[2,1]=2
L[3,2]=3
L[4,3]=4

print(L)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
O = np.zeros((10,10))
O[0,:] = 1
O[9,:]=1
O[:,0] = 1
O[:,9]=1
print(O)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Exercise 3

In [ ]:
import numpy as np

Create two matrices A and B: $$A=\left(\begin{array}{cc}
    1 & 2  \\
    4 & -1  \\
\end{array}\right) \text{ and } B=\left(\begin{array}{cc}
    4 & -2  \\
    -6 & 3  \\
\end{array}\right).$$

1. Compute the matrices $C_1 = A + B$ and $C_2 = A − B$.
2. Compute the matrix products $D_1 = A \cdot B$ and $D_2 = B \cdot A$ (element wise).
3. Are A and B singular? If not, then compute their inverse.

In [ ]:
A=np.array([[1,2],[4,-1]])
B=np.array([[4,-2],[-6,3]])
print(A)
print(B)

[[ 1  2]
 [ 4 -1]]
[[ 4 -2]
 [-6  3]]


In [ ]:
C_1 = A+B
print(C_1)

[[ 5  0]
 [-2  2]]


In [ ]:
C_2=A-B

In [ ]:
print(C_2)

[[-3  4]
 [10 -4]]


In [ ]:
D_1=np.dot(A,B)
print(D_1)

[[ -8   4]
 [ 22 -11]]


In [ ]:
D_2=np.dot(B,A)
print(D_2)

[[ -4  10]
 [  6 -15]]


In [ ]:
np.linalg.inv(A)

array([[ 0.11111111,  0.22222222],
       [ 0.44444444, -0.11111111]])

In [ ]:
np.linalg.inv(B)

array([[-4.50359963e+15, -3.00239975e+15],
       [-9.00719925e+15, -6.00479950e+15]])