In [1]:
import numpy as np

# Naive Gauss Elimination

Find $x = (x_1, x_2,x_3,x_4)$ such that

$$\left\{
\begin{array}{rcrcrcrc}
x_1 & - & x_2 & +  & 2x_3  & - & x_4 & = & -8\\
x_1& + & x_2 & + & x_3 &  & & = & -2\\
2x_1& - & 2x_2 & + & 3x_3 & - & 3x_4 & = & -20\\
x_1& - & x_2& + & 4x_3 & + & 3x_4 & = & 4
\end{array}
\right.$$

Show, by hand, that the solution is $x = (-7, 3, 2, 2)$

In [9]:
A = np.array([[1, -1, 2, -1],
              [1,  1, 1,  0],
              [2, -2, 3, -3],
              [1, -1, 4,  3]])
print('A =\n', A)

y = np.array([-8, -2, -20, 4])
print('y =\n', y)

A =
 [[ 1 -1  2 -1]
 [ 1  1  1  0]
 [ 2 -2  3 -3]
 [ 1 -1  4  3]]
y =
 [ -8  -2 -20   4]


Construct the augmented matrix.

In [10]:
n,col = A.shape

Aug = np.zeros((n,n+1))
Aug[:,0:n] = A
Aug[:,-1] = y

print(Aug)

[[  1.  -1.   2.  -1.  -8.]
 [  1.   1.   1.   0.  -2.]
 [  2.  -2.   3.  -3. -20.]
 [  1.  -1.   4.   3.   4.]]


Elimination step

In [14]:
for i in range(n-1):
  for j in range(i+1,n):
    m = Aug[j,i]/Aug[i,i]
    Aug[j,i:n+1] = Aug[j,i:n+1] - m*Aug[i,i:n+1]
  print('Row',i+1,':\n', Aug)

Row 1 :
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]
Row 2 :
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0. nan inf inf inf]
 [ 0. nan nan nan nan]]
Row 3 :
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0. nan inf inf inf]
 [ 0. nan nan nan nan]]


<ipython-input-14-e819454bfc4d>:3: RuntimeWarning: divide by zero encountered in scalar divide
  m = Aug[j,i]/Aug[i,i]
<ipython-input-14-e819454bfc4d>:4: RuntimeWarning: invalid value encountered in multiply
  Aug[j,i:n+1] = Aug[j,i:n+1] - m*Aug[i,i:n+1]
<ipython-input-14-e819454bfc4d>:3: RuntimeWarning: invalid value encountered in scalar divide
  m = Aug[j,i]/Aug[i,i]


Backward substitution

In [5]:
x = np.zeros(n)
x[-1] = Aug[-1,-1]/Aug[-1,-2]
for i in range(n-2,-1,-1):
  x[i] = (Aug[i,-1] - sum(Aug[i,i:n]*x[i:n]))/Aug[i,i]
print('Solution:', x)

Solution: [-7.  3.  2.  2.]


# Gauss Elimination with Partial Pivoting

Consider the linear system

$$\left\{
\begin{array}{rcrcrcrc}
x_1 & - & x_2 & +  & 2x_3  & - & x_4 & = & -8\\
2x_1& - & 2x_2 & + & 3x_3 & - & 3x_4 & = & -20\\
x_1& + & x_2 & + & x_3 &  & & = & -2\\
x_1& - & x_2& + & 4x_3 & + & 3x_4 & = & 4
\end{array}
\right.$$

The solution is $x = (-7, 3, 2, 2)$

In [15]:
A = np.array([[1, -1, 2, -1],
              [2, -2, 3, -3],
              [1,  1, 1,  0],
              [1, -1, 4,  3]])
print('A =\n', A)

y = np.array([-8, -20, -2, 4])
print('y =\n', y)

A =
 [[ 1 -1  2 -1]
 [ 2 -2  3 -3]
 [ 1  1  1  0]
 [ 1 -1  4  3]]
y =
 [ -8 -20  -2   4]


Construct the augmented matrix

In [16]:
n,col = A.shape

Aug = np.zeros((n,n+1))
Aug[:,0:n] = A
Aug[:,-1] = y

print(Aug)

[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


Elimination step with partial pivoting

In [17]:
for i in range(n-1):
  # partial pivoting
  p = i
  for k in range(i,n):
    if Aug[k,i] > Aug[p,i]:
      p = k
  Aug[[p,i]] = Aug[[i,p]] # swap rows
  for j in range(i+1,n):
    m = Aug[j,i]/Aug[i,i]
    Aug[j,i:n+1] = Aug[j,i:n+1] - m*Aug[i,i:n+1]
  print('Row',i+1,':\n', Aug)

Row 1 :
 [[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]]
Row 2 :
 [[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    0.    2.5   4.5  14. ]]
Row 3 :
 [[  2.   -2.    3.   -3.  -20. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]


Backward substitution

In [18]:
x = np.zeros(n)
x[-1] = Aug[-1,-1]/Aug[-1,-2]
for i in range(n-2,-1,-1):
  x[i] = (Aug[i,-1] - sum(Aug[i,i:n]*x[i:n]))/Aug[i,i]
print('Solution:', x)

Solution: [-7.  3.  2.  2.]


# Computational Cost

In [22]:
def gauss(A,y):
  n,col = A.shape

  Aug = np.zeros((n,n+1))
  Aug[:,0:n] = A
  Aug[:,-1] = y

  for i in range(n-1):
    # partial pivoting
    p = i
    for k in range(i,n):
      if Aug[k,i] > Aug[p,i]:
        p = k
    Aug[[p,i]] = Aug[[i,p]] # swap rows
    for j in range(i+1,n):
      m = Aug[j,i]/Aug[i,i]
      Aug[j,i:n+1] = Aug[j,i:n+1] - m*Aug[i,i:n+1]
  x = np.zeros(n)
  x[-1] = Aug[-1,-1]/Aug[-1,-2]
  for i in range(n-2,-1,-1):
    x[i] = (Aug[i,-1] - sum(Aug[i,i:n]*x[i:n]))/Aug[i,i]
  return x

In [25]:
n = 500
A = 0.1*np.random.randn(n,n)
y = np.random.randn(n)
np.linalg.det(A)

1.1924141711456226e+64

In [26]:
%timeit gauss(A,y)

676 ms ± 23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Hands-on Activity



Write a code that solves a given linear system using Gauss-Jordan method. Using your code, solve the linear system

$$\left\{
\begin{array}{rcrcrcrc}
x_1 & - & x_2 & +  & 2x_3  & - & x_4 & = & -8\\
2x_1& - & 2x_2 & + & 3x_3 & - & 3x_4 & = & -20\\
x_1& + & x_2 & + & x_3 &  & & = & -2\\
x_1& - & x_2& + & 4x_3 & + & 3x_4 & = & 4
\end{array}
\right.$$

Which is computationally cheaper: Gaussian elimination or Gauss-Jordan method?

In [27]:
# Write your code here.
A = np.array([[1, -1, 2, -1],
              [2, -2, 3, -3],
              [1,  1, 1,  0],
              [1, -1, 4,  3]])
print('A =\n', A)

y = np.array([-8, -20, -2, 4])
print('y =\n', y)

A =
 [[ 1 -1  2 -1]
 [ 2 -2  3 -3]
 [ 1  1  1  0]
 [ 1 -1  4  3]]
y =
 [ -8 -20  -2   4]


In [28]:
n,col = A.shape

Aug = np.zeros((n,n+1))
Aug[:,0:n] = A
Aug[:,-1] = y

print(Aug)

[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [34]:
for i in range(n):
  # partial pivoting
  p = i
  for k in range(i,n):
    if Aug[k,i] > Aug[p,i]:
      p = k
  Aug[[p,i]] = Aug[[i,p]] # swap rows
  for j in range(n):
    if j!=i :
      m = Aug[j,i]/Aug[i,i]
      Aug[j,i:n+1] = Aug[j,i:n+1] - m*Aug[i,i:n+1]
  print('Row',i+1,':\n', Aug)

Row 1 :
 [[  2.    0.    0.   -6.  -26. ]
 [  0.    2.    0.    2.4  10.8]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]
Row 2 :
 [[  2.    0.    0.   -6.  -26. ]
 [  0.    2.    0.    2.4  10.8]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]
Row 3 :
 [[  2.    0.    0.   -6.  -26. ]
 [  0.    2.    0.    2.4  10.8]
 [  0.    0.    2.5   4.5  14. ]
 [  0.    0.    0.   -0.4  -0.8]]
Row 4 :
 [[  2.    0.    0.    0.  -14. ]
 [  0.    2.    0.    0.    6. ]
 [  0.    0.    2.5   0.    5. ]
 [  0.    0.    0.   -0.4  -0.8]]


In [35]:
x = np.zeros(n)
for i in range(n):
  x[i] = Aug[i,-1]/Aug[i,i]
print('Solution:', x)

Solution: [-7.  3.  2.  2.]


# Try this!





Write a code that outputs the determinant (or inverse, if you wish) of a given square matrix using Gauss elimination or Gauss-Jordan method.

In [ ]:
# Write your code here.
